# Docker Compose file for development
version: "2"
services:

  db:
    extends:
      file: ./common.yml
      service: db
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata:z
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"

  critiquebrainz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../:/code:z
      - ../data/app:/data:z
    ports:
      - "80:80"
    depends_on:
      - db
      - critiquebrainz_redis
      - musicbrainz_db
      - static_builder

  critiquebrainz_redis:
    image: redis:4.0-alpine

  musicbrainz_db:
    image: metabrainz/musicbrainz-test-database:beta
    volumes:
      - ../data/mbdata:/var/lib/postgresql/data/pgdata:z
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      MB_IMPORT_DUMPS: "true"
    ports:
      - "5430:5432"

  static_builder:
    build:
      context: ..
      dockerfile: Dockerfile.webpack
    command: npm run dev
    volumes:
      - ..:/code:z
