version: "2"
services:

  consul:
    command: -server -bootstrap
    image: progrium/consul
    network_mode: "host"
    ports:
      - "8500:8500"

  git2consul:
    command: --endpoint 127.0.0.1 --port 8500 --config-file /etc/git2consul.d/config.json
    image: cimpress/git2consul
    restart: always
    depends_on:
      - consul
    network_mode: "host"
    volumes:
      - ../:/tmp/critiquebrainz.git
      - ./git2consul:/etc/git2consul.d

  critiquebrainz:
    build:
        context: ..
        dockerfile: ./Dockerfile
    network_mode: "host"
    environment:
      DEPLOY_ENV: prod
    depends_on:
      - db
    volumes:
      - ../:/code
      - ../data/app:/data

  db:
    build:
      context: ./pg_custom/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: critiquebrainz
      POSTGRES_PASSWORD: critiquebrainz
      POSTGRES_DB: critiquebrainz
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata


