# Compose file for use on production servers.
version: "2"
services:

  critiquebrainz:
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DEPLOY_ENV: "prod"
      SERVICE_13032_NAME: "critiquebrainz"
      SERVICE_13032_CHECK_TCP: "true"
      SERVICE_13032_CHECK_INTERVAL: "15s"
      SERVICE_13032_CHECK_TIMEOUT: "3s"
    links:
      - critiquebrainz-redis
    volumes:
      - critiquebrainz-data:/data
    network_mode: bridge
    ports:
      - "13032:13032"

  critiquebrainz-nginx:
    build:
      context: ./nginx_custom
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DEPLOY_ENV: "prod"
      SERVICE_64080_NAME: "critiquebrainz-nginx"
      SERVICE_64080_CHECK_HTTP: "/"
      SERVICE_64080_CHECK_INTERVAL: "15s"
      SERVICE_64080_CHECK_TIMEOUT: "3s"
    links:
      - critiquebrainz
    network_mode: bridge
    ports:
      - "64080:64080"

  critiquebrainz-redis:
    image: redis:3.2.1
    restart: always
    network_mode: bridge

volumes:
  critiquebrainz-data:
    external: true
