# Docker Compose file for development
version: "2"
services:

  db:
    extends:
      file: ./common.yml
      service: db
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata:z
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"

  db_test:
    build:
      context: ./pg_custom/
      dockerfile: Dockerfile
    command: postgres -F
    environment:
      POSTGRES_USER: critiquebrainz
      POSTGRES_PASSWORD: critiquebrainz
      POSTGRES_DB: critiquebrainz

  critiquebrainz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../:/code:z
      - ../data/app:/data:z
    ports:
      - "80:80"
    depends_on:
      - db
      - db_test
      - critiquebrainz_redis
      - musicbrainz_db

  critiquebrainz_redis:
    image: redis:4.0-alpine

  musicbrainz_db:
    image: metabrainz/musicbrainz-test-database:beta
    volumes:
      - ../data/mbdata:/var/lib/postgresql/data/pgdata:z
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      MB_IMPORT_DUMPS: "true"
    ports:
      - "5430:5432"
