# Docker Compose file for testing
version: "2"
services:

  db_test:
    build:
      context: ./pg_custom/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: critiquebrainz
      POSTGRES_PASSWORD: critiquebrainz
      POSTGRES_DB: critiquebrainz
    command: postgres -F
    network_mode: bridge

  musicbrainz_db:
    image: ferbncode/musicbrainz-test-database:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    network_mode: bridge

  critiquebrainz_redis:
    image: redis:4.0-alpine
    network_mode: bridge

  critiquebrainz_test:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.test
    links:
      - db_test
      - musicbrainz_db
      - critiquebrainz_redis
    network_mode: bridge
